### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by roscoevanderboom** [AhKi/oh-my-desk#137]
Hi there. This project is awesome, I have had something similar in mind for a while. I'm not a great coder, but my English is pretty good. I'd be happy to do some editing on your docs.

**Comment by HyunmoAhn** [comment]
I’m glad you’re interested.
We need to your help for documentation because our native language is not English….😢

I wonder which documents you want to look at and make improvements.
I know that master branch, latest release version 1.1.2 about oh-my-desk, has README.md and wiki
But wiki will be deprecated after released v2.0 because I think wiki is a bad way to stay up to date. So, If you edit documentation of wiki, It will be a waste of time for you. I prepare documentation about version 2.0 in README.md code.

show this link for prepare document(will be released)
action documentation
main documentation
renderer documentation
store documentation)

We would appreciate it if you could give us some other improvements in documentation except part of wiki.

Actually, I would like to ask you to document version 2.0, but It would be rude to do that because the version 2.0 code has not yet been released! If you are still interested in our project after we release 2.0(maybe 1 to 2 month later), please do so again.

If you have any questions, please leave a Comment. Thank you.

**Comment by roscoevanderboom** [comment]
This project has great potential, and it already looks very clean!! I would love to contribute in any way I can. My understanding of some code is limited but I can manage general things. I also think it's important to present the project in a way that is easy for users and interesting for developers at the same time.

I don't think wiki is the best place to post documentation. We can set up the Github page with links to blogs or other docs that are not included in the project Readme. Many of projects show a lot of documentation in Github, but I think a nice website is better. Especially for non-coders.

**Comment by roscoevanderboom** [comment]
Also, Riot, or Slack are good places to discuss things.

**Comment by HyunmoAhn** [comment]
> Also, Riot, or Slack are good places to discuss things.

Ok. I will prepare `Slack` Open Channel. Please wait a one or two days.

> but I think a nice website is better. Especially for non-coders.

I agree with your opinion. I search about it. I found [GitBook](https://www.gitbook.com/) used in [Redux-documentation](https://redux.js.org/)
 Do you know any other service that is better than `GitBook`?

**Comment by roscoevanderboom** [comment]
GitBook looks great! I thought about making a site and hosting on Google Firebase, but the layout on the Redux page looks very professional and easy to navigate.

**Comment by HyunmoAhn** [comment]
[Join Oh-My-Desk Open Community in slack](https://join.slack.com/t/oh-my-desk/shared_invite/enQtNDUyMjM4MzA0NTk1LTJjYzM2YWNiZmNkMDI4ODAwNDAzYTljYzNkZDc1MTU1YTQxNGViMTZjZGFlOWUxZTM1OWM0YWU4YzEwNzIzMDI)

Anybody who want discuss about `oh-my-desk` can join slack.
It is official public slack about `oh-my-desk`.  
You can leave any message in slack.  

@roscoevanderboom Join slack using above link.
